# Generated by Django 6.0 on 2026-05-23 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('C', 'Center'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('LD', 'Left Defense'), ('RD', 'Right Defense'), ('G', 'Goalie')], max_length=2)),
                ('secondary_position', models.CharField(blank=True, choices=[('C', 'Center'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('LD', 'Left Defense'), ('RD', 'Right Defense'), ('G', 'Goalie')], max_length=2, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3)),
                ('conference', models.CharField(choices=[('east', 'Eastern'), ('west', 'Western')], max_length=20)),
                ('division', models.CharField(choices=[('atlantic', 'Atlantic'), ('metropolitan', 'Metropolitan'), ('central', 'Central'), ('pacific', 'Pacific')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyout_year', models.CharField(blank=True, help_text='Season the buyout occured in 2019-20 format', max_length=7, null=True)),
                ('total_years', models.PositiveIntegerField()),
                ('total_value', models.PositiveIntegerField()),
                ('aav', models.PositiveIntegerField()),
                ('signing_date', models.DateField(blank=True, null=True)),
                ('start_season', models.CharField(max_length=7)),
                ('end_season', models.CharField(max_length=7)),
                ('status', models.CharField(choices=[('active', 'Active'), ('future', 'Future'), ('bought_out', 'Bought Out'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='active', max_length=15)),
                ('expiration_status', models.CharField(choices=[('ufa', 'UFA'), ('rfa', 'RFA'), ('10.2c', '10.2(c)')], default='ufa', help_text='Free agency status when contract ends', max_length=10)),
                ('is_two_way', models.BooleanField(default=False)),
                ('is_entry_level', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='caps.player')),
                ('buyout_team', models.ForeignKey(blank=True, help_text='Team that actually bought out the contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyout_contracts', to='caps.team')),
                ('signing_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to='caps.team')),
            ],
        ),
        migrations.CreateModel(
            name='RetainedSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('retention_percentage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retained_salaries', to='caps.contract')),
                ('retaining_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retained_contracts', to='caps.team')),
            ],
            options={
                'verbose_name_plural': 'Retained Salaries',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='caps.team'),
        ),
        migrations.CreateModel(
            name='CapHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=7)),
                ('cap_hit', models.PositiveIntegerField()),
                ('nhl_salary', models.PositiveIntegerField()),
                ('ahl_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('signing_bonus', models.PositiveIntegerField(default=0)),
                ('roster_status', models.CharField(choices=[('active', 'Active'), ('buried', 'Buried'), ('ir', 'Injured Reserve'), ('ltir', 'Long-Term IR')], default='active', max_length=10)),
                ('has_nmc', models.BooleanField(default=False)),
                ('has_ntc', models.BooleanField(default=False)),
                ('has_modified_ntc', models.BooleanField(default=False)),
                ('ntc_teams_can_block', models.PositiveIntegerField(blank=True, null=True)),
                ('performance_bonus_potential', models.PositiveIntegerField(default=0)),
                ('performance_bonus_earned', models.PositiveIntegerField(default=0)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_hits', to='caps.contract')),
            ],
            options={
                'verbose_name_plural': 'Cap Hits',
                'unique_together': {('contract', 'season')},
            },
        ),
        migrations.CreateModel(
            name='DraftPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('round', models.PositiveSmallIntegerField(choices=[(1, 'Round 1'), (2, 'Round 2'), (3, 'Round 3'), (4, 'Round 4'), (5, 'Round 5'), (6, 'Round 6'), (7, 'Round 7')])),
                ('is_conditional', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Condition details, trade notes, etc.')),
                ('current_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_picks', to='caps.team')),
                ('original_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_picks', to='caps.team')),
            ],
            options={
                'ordering': ['year', 'round'],
                'unique_together': {('year', 'round', 'original_team')},
            },
        ),
        migrations.CreateModel(
            name='CapPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=7)),
                ('amount', models.PositiveIntegerField()),
                ('penalty_type', models.CharField(choices=[('bonus_carryover', 'Performance Bonus Carryover'), ('bonus_cushion', 'Performance Bonus Cushion Excess'), ('ltir_opening', 'Season Opening LTIR')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Penalty details')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_penalties', to='caps.team')),
            ],
            options={
                'verbose_name_plural': 'Cap penalties',
                'unique_together': {('team', 'season', 'penalty_type')},
            },
        ),
    ]
