# Generated by Django 6.0 on 2026-01-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='has_modified_ntc',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='has_nmc',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='has_ntc',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ntc_teams_can_block',
        ),
        migrations.AddField(
            model_name='caphit',
            name='has_modified_ntc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caphit',
            name='has_nmc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caphit',
            name='has_ntc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caphit',
            name='ntc_teams_can_block',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
