# Generated by Django 6.0 on 2026-01-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_remove_contract_has_modified_ntc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caphit',
            name='performance_bonus_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caphit',
            name='performance_bonus_potential',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('bought_out', 'Bought Out'), ('terminated', 'Terminated'), ('expired', 'Expired'), ('future', 'Future')], default='active', max_length=15),
        ),
    ]
