# Generated by Django 6.0 on 2026-01-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0003_caphit_performance_bonus_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='secondary_position',
            field=models.CharField(blank=True, choices=[('C', 'Center'), ('LW', 'Left Wing'), ('RW', 'Right Wing'), ('LD', 'Left Defense'), ('RD', 'Right Defense'), ('G', 'Goalie')], max_length=2, null=True),
        ),
    ]
