# Generated by Django 6.0 on 2026-02-18 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0004_player_secondary_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='buyout_team',
            field=models.ForeignKey(blank=True, help_text='Team that actually bought out the contract', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyout_contracts', to='caps.team'),
        ),
        migrations.AddField(
            model_name='contract',
            name='buyout_year',
            field=models.CharField(blank=True, help_text='Season the buyout occured in 2019-20 format', max_length=7, null=True),
        ),
    ]
