# Generated by Django 6.0 on 2026-02-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0005_contract_buyout_team_contract_buyout_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='free_agent_status',
            field=models.CharField(choices=[('ufa', 'UFA'), ('rfa', 'RFA'), ('10.2c', '10.2(c)')], default='ufa', help_text='Free agency status when contract ends', max_length=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('future', 'Future'), ('bought_out', 'Bought Out'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='active', max_length=15),
        ),
    ]
