# Generated by Django 6.0 on 2026-02-20 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0006_contract_free_agent_status_alter_contract_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='free_agent_status',
            new_name='expiration_status',
        ),
    ]
