# Generated by Django 6.0 on 2026-02-24 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0007_rename_free_agent_status_contract_expiration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusOverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=7)),
                ('amount', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, help_text='which players bonuses caused overage')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_overages', to='caps.team')),
            ],
            options={
                'verbose_name_plural': 'Bonus overages',
                'unique_together': {('team', 'season')},
            },
        ),
    ]
