# Generated by Django 6.0 on 2026-03-01 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0008_bonusoverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=7)),
                ('amount', models.PositiveIntegerField()),
                ('penalty_type', models.CharField(choices=[('bonus_carryover', 'Performance Bonus Carryover'), ('bonus_cushion', 'Performance Bonus Cushion Excess'), ('ltir_opening', 'Season Opening LTIR')], max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Penalty details')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_penalties', to='caps.team')),
            ],
            options={
                'verbose_name_plural': 'Cap penalties',
                'unique_together': {('team', 'season', 'penalty_type')},
            },
        ),
        migrations.DeleteModel(
            name='BonusOverage',
        ),
    ]
